[package]
name = "rose_update"
version = "0.2.0"
authors = ["Ralph Minderhoud <ralph@rednim.com>"]
edition = "2021"

[dependencies]
anyhow = "1.0"
async-stream = "0.3.5"
async-trait = "0.1"
bitar = { version = "0.10.0", features = ["compress", "zstd-compression"] }
clap = { version = "3.2.16", features = ["derive"] }
directories = "5.0"
eframe = { version = "0.23", features = ["wgpu"] }
egui_extras = { version = "0.23", features = ["image", "svg"] }
futures = "0.3"
humansize = "1.1"
path-slash = "0.2.1"
open = "3.0"
reqwest = { version = "0.11", default-features = false, features = [
    "brotli",
    "deflate",
    "gzip",
    "json",
    "rustls-tls",
    "stream",
] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
time = { version = "0.3", features = ["serde-well-known"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tokio = { version = "1", features = ["full"] }
walkdir = "2"

# Only needed for bitar_ext
futures-util = { version = "0.3", default-features = false, features = ["std"] }

# Feature: console
console-subscriber = { version = "0.1.7", optional = true }

[build-dependencies]
winresource = "0.1"

[target.'cfg(windows)'.dependencies]
windows = { version = "0.39.0", features = ["Win32_System_Threading"] }

[features]
console = ["tokio/tracing", "console-subscriber"]
